### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by IonicaBizau** [vjeux/jsMatch#3]
@vjeux I'd like to publish a package on npm with the same name (`match`) and I was wondering if you still maintain this package (seems it didn't get any updates since 4 years ago) and if you'd like to `npm unpublish` it.

Of course, there is no problem if you don't want to, but like I said, I'd like to publish a thingy with the same name. :smile: 

Thanks! :cake:

**Comment by vjeux** [comment]
Absolutely! I didn't even remember that I had this package :p

**Comment by vjeux** [comment]
Done, it's all yours!

**Comment by IonicaBizau** [comment]
@vjeux Oh, thank you so much! :sparkles: You were fast. :rocket:
